#!/bin/sh

. ./_init

# args
if [ $# -ne 1 ]; then
        printf "Usage: ./show_account_id_from_login login\n"
        exit 1
fi
login="$1"

data=`./_get_account_id_from_login ${login}`

printf "${data}\n"
